### ISSUE TITLE
Addon appears to break in fastboot.

### ISSUE THREAD

**Issue by alexmasita** [cibernox/ember-power-datepicker#26]
Part of the error reads as follows: 

```
There was an error running your app in fastboot. More info about the error:
 TypeError: Cannot set property 'compare' of undefined
    at Module.callback (/Users/alexmasita/External/Personal/projects/Ember-Apps/mobile-services/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-mBr0WNFq.tmp/assets/addon-tree-output/moment/index.js:23:1)
    at Module.exports (/Users/alexmasita/External/Personal/projects/Ember-Apps/mobile-services/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-mBr0WNFq.tmp/assets/vendor/loader/loader.js:106:1)
```

**Comment by cibernox** [comment]
I don't think that this error message is coming from that addon. Can you provide a reproduction?
